import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Modern BLVD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-midnight-500'>
        <h1 className='font-bold text-5xl text-white-500'>Hello World</h1>
      </div>
    </>
  )
}

export default Home
